INSERT INTO CATEGORY(NAME,DESCRIPTION) values ('SEDAN','Samochód typowy osobowy')
INSERT INTO CATEGORY(NAME,DESCRIPTION) values ('KOMBI','Samochód z dużą paką mozna wizoic cegły i deski -  osobowy')


Insert into CAR(BRAND,MODEL,YEAR,COLOR, FUEL_TYPE,GEAR_BOX,VIN_NUMBER,CATEGORY_ID) values('AUDI','A4',2012,'CZARNY','DIESEL','AUTOMAT','HD34','1')
Insert into CAR(BRAND,MODEL,YEAR,COLOR, FUEL_TYPE,GEAR_BOX,VIN_NUMBER,CATEGORY_ID) values('TOYOTA','PRIUS',2015,'SREBRNY','HYBRYDA','AUTOMAT','SCV56','2')
Insert into CAR(BRAND,MODEL,YEAR,COLOR, FUEL_TYPE,GEAR_BOX,VIN_NUMBER,CATEGORY_ID) values('FIAT','PANDA',2016,'CZERWONY','BENZYNA','MANUALNA','PK87','1')


insert into CLIENT (NAME,LAST_NAME,ADDRES,PHONE_NUMBER) values ('JAN','KOWALSKI','LUBLIN - GŁĘBOKA 325/45','345123345')
insert into CLIENT (NAME,LAST_NAME,ADDRES,PHONE_NUMBER) values ('ROMAN','NOWAK','KRAKÓW - SŁONECZNA 45/12','999999999')




